name: Test Automation Pipeline

on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------
      # Checkout source code
      # ----------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v7

      # ----------------------------------------
      # Set up Java 25 LTS
      # ----------------------------------------
      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      # ----------------------------------------
      # Verify Java and Maven
      # ----------------------------------------
      - name: Verify Java and Maven
        run: |
          java --version
          mvn --version

      # ----------------------------------------
      # Build and compile
      # ----------------------------------------
      - name: Build and compile
        run: mvn clean compile

      # ----------------------------------------
      # Run TestNG tests
      # ----------------------------------------
      - name: Run tests
        env:
          # Credentials from GitHub Secrets
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

          # Test configuration
          BROWSER: chrome
          URL: https://practicesoftwaretesting.com/auth/login
          HEADLESS: true
          EXPLICIT_WAIT: 10
          PAGE_LOAD_TIMEOUT: 30

        run: mvn test

      # ----------------------------------------
      # Prepare to upload ExtentReport to
      # Github pages
      # ----------------------------------------
      - name: Prepare GitHub Pages
        if: always()
        run: |
          mkdir -p site

          if [ -d reports ]; then
            cp -R reports/. site/
          else
            echo "<h1>ExtentReport was not generated</h1>" > site/index.html
          fi

          echo "===== GitHub Pages contents ====="
          find site -type f -print

      # ----------------------------------------
      # Upload artifacts
      # ----------------------------------------
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # ----------------------------------------
      # Deploy to Github pages
      # ----------------------------------------
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
